TG5_BuildableVehiclesConfig {
 m_sBuildableLandVehicles {
  TG5_BuildableVehicleEntry "{6A731C8CF1409318}" {
   m_ResourceName "{0FBF8F010F81A4E5}Prefabs/Vehicles/Wheeled/LAV25/LAV25.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8CED881D25}" {
   m_ResourceName "{F649585ABB3706C4}Prefabs/Vehicles/Wheeled/M151A2/M151A2.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8CEDB3C504}" {
   m_ResourceName "{F6B23D17D5067C11}Prefabs/Vehicles/Wheeled/M151A2/M151A2_M2HB.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8CEC5B8178}" {
   m_ResourceName "{47D94E1193A88497}Prefabs/Vehicles/Wheeled/M151A2/M151A2_transport.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8C83FA487B}" {
   m_ResourceName "{92264FF932676C13}Prefabs/Vehicles/Wheeled/M923A1/M923A1_ammo.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8C83E1761E}" {
   m_ResourceName "{1FF144F8A209239D}Prefabs/Vehicles/Wheeled/M923A1/M923A1_arsenal.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8C8387636A}" {
   m_ResourceName "{36BDCC88B17B3BFA}Prefabs/Vehicles/Wheeled/M923A1/M923A1_command.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8C83A5BC25}" {
   m_ResourceName "{2D74C39A650A3030}Prefabs/Vehicles/Wheeled/M923A1/M923A1_engineer.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8C827CA4F4}" {
   m_ResourceName "{A042ACE5C2B13206}Prefabs/Vehicles/Wheeled/M923A1/M923A1_repair.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8C8210E0E8}" {
   m_ResourceName "{2BE1F8B9299B67C1}Prefabs/Vehicles/Wheeled/M923A1/M923A1_tanker.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8C822A03B9}" {
   m_ResourceName "{F1FBD0972FA5FE09}Prefabs/Vehicles/Wheeled/M923A1/M923A1_transport.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8C82C3652B}" {
   m_ResourceName "{81FDAD5EB644CC3D}Prefabs/Vehicles/Wheeled/M923A1/M923A1_transport_covered.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8C567FD2AB}" {
   m_ResourceName "{4A71F755A4513227}Prefabs/Vehicles/Wheeled/M998/M1025.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8C561AF965}" {
   m_ResourceName "{3EA6F47D95867114}Prefabs/Vehicles/Wheeled/M998/M1025_armed_M2HB.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8C5601571C}" {
   m_ResourceName "{3B1EB924602C7A07}Prefabs/Vehicles/Wheeled/M998/M997_maxi_ambulance_MERDC.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8C56920CC7}" {
   m_ResourceName "{B55C6990A6A9411B}Prefabs/Vehicles/Wheeled/M998/M998_covered.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8C56BE2031}" {
   m_ResourceName "{9B1BF9644E0378D6}Prefabs/Vehicles/Wheeled/M998/M998_covered_long.et"
  }
  TG5_BuildableVehicleEntry "{6A731C8C5159A23F}" {
   m_ResourceName "{5674FAEB9AB7BDD0}Prefabs/Vehicles/Wheeled/M998/M998_uncovered.et"
  }
 }
 m_sBuildableAirVehicles {
  TG5_BuildableVehicleEntry "{6A731C8C6CE49F4B}" {
   m_ResourceName "{CB6215B3B44EA463}Prefabs/Vehicles/Helicopters/UH1H/SP02_GUNSHIP.et"
   m_eDomain AIR
  }
  TG5_BuildableVehicleEntry "{6A731C8C18DC33F9}" {
   m_ResourceName "{350492BE6F09A847}Prefabs/Vehicles/Helicopters/UH1H/UH1H_armed_gunship_HE_sharkNose.et"
   m_eDomain AIR
  }
  TG5_BuildableVehicleEntry "{6A731C8C18FEA1C9}" {
   m_ResourceName "{3133602B406D131C}Prefabs/Vehicles/Helicopters/UH1H/UH1H_armed_gunship_HEDP_sharkNose.et"
   m_eDomain AIR
  }
  TG5_BuildableVehicleEntry "{6A731C8C18987EEE}" {
   m_ResourceName "{EEE291940A9DA42A}Prefabs/Vehicles/Helicopters/UH1H/UH1H_sharkNose.et"
   m_eDomain AIR
  }
  TG5_BuildableVehicleEntry "{6A731C8C18BCB26C}" {
   m_ResourceName "{00BC1E407D536A34}Prefabs/Vehicles/Helicopters/UH1H/UH1H_armed_sharkNose.et"
   m_eDomain AIR
  }
  TG5_BuildableVehicleEntry "{6A731C8C338D0D9F}" {
   m_ResourceName "{70BAEEFC2D3FEE64}Prefabs/Vehicles/Helicopters/UH1H/UH1H.et"
  }
 }
}